version: "3"

services:
  app:
    build: .
    container_name: chess
    environment:
      - VIRTUAL_HOST=chess.kuuhaku.dev
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
